### ISSUE TITLE
[Feature Request] Fading out background music when player begins playing the instruments

### ISSUE THREAD

**Issue by Snownee** [Aeronica/BardMania#6]

**Comment by Aeronica** [comment]
Added this feature to the repository
[4a38b87c3730e3e0d2a4a34d3ac48344ee34ef14](https://github.com/Aeronica/BardMania/commit/4a38b87c3730e3e0d2a4a34d3ac48344ee34ef14)
[a98551b765dd6ae09e62418d8f0c631a80642b9a](https://github.com/Aeronica/BardMania/commit/a98551b765dd6ae09e62418d8f0c631a80642b9a)

I want to reconcile some sound channel configuration differences between this mod and [mxTune ](https://minecraft.curseforge.com/projects/mxtune) before pushing another alpha version.

**Comment by Aeronica** [comment]
2018-09-07 bard-mania_1.12.2-0.10.0-alpha
Additions:
- [Feature Request #6] Stop background music when playing an instrument.

A fade out would be nicer, but I had some difficulty with the MusicTicker and access transformers. This will take some experimentation, The "Dynamic Surroundings" mod repository has many examples I can study. For now this will work.
