### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Snownee** [Aeronica/BardMania#7]
https://paste.ubuntu.com/p/V8MPKckftR/

**Comment by Aeronica** [comment]
Verified.  Yes I did a stupid thing. Fix will be out soon.

**Comment by Aeronica** [comment]
Crash occurs when background music or jukebox record plays. That is when any streaming source other than a NoteSound. Corrected by checking for an instance of NoteSound first.

2018-08-29 bard-mania_1.12.2-0.9.0-alpha
Fixes Crash:
    https://github.com/Aeronica/BardMania/issues/7
    Time: 8/30/18 2:14 PM
    Description: Unexpected error

    java.lang.ClassCastException: net.minecraft.client.audio.PositionedSoundRecord cannot be cast to net.aeronica.mods.bard_mania.client.audio.NoteSound
    	at net.aeronica.mods.bard_mania.client.audio.SoundHelper.PlayStreamingSourceEvent(SoundHelper.java:122)
